import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  gradientOverlay2: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.5,
  },
  shimmer: {
    position: 'absolute',
    top: 0,
    width: SCREEN_WIDTH * 0.3,
    height: SCREEN_HEIGHT,
    opacity: 0.3,
  },
  avatar: {
    position: 'absolute',
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  glowRing: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    opacity: 0.6,
  },
  avatarCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 8,
  },
  avatarEmoji: {
    fontSize: 28,
  },
  connectingLine: {
    position: 'absolute',
    height: 3,
    backgroundColor: 'rgba(138, 43, 226, 0.5)',
    borderRadius: 1.5,
  },
  lineGlow: {
    position: 'absolute',
    width: '100%',
    height: 8,
    borderRadius: 4,
    top: -2.5,
    left: 0,
  },
  lineDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    right: 0,
    top: -2.5,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 4,
  },
  lineMovingDot: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    right: 0,
    top: -1.5,
  },
  privacyIcon: {
    position: 'absolute',
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconGlow: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    opacity: 0.5,
  },
  privacyIconText: {
    fontSize: 28,
  },
  particle: {
    position: 'absolute',
  },
  aiBlob: {
    position: 'absolute',
    overflow: 'hidden',
  },
  blobInner: {
    position: 'absolute',
    width: '70%',
    height: '70%',
    borderRadius: 1000,
    top: '15%',
    left: '15%',
    opacity: 0.8,
  },
  blobOuter: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 1000,
    opacity: 0.6,
  },
  abstractShape: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shapeInner: {
    width: '80%',
    height: '80%',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 30,
    borderRightWidth: 30,
    borderBottomWidth: 50,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'rgba(99, 102, 241, 0.4)',
  },
});

export default styles;

